#!/bin/bash

KERNEL_DIRS=(
  "src/blas"
  "src/activations"
  "src/attention"
)

mkdir -p src/kernels

INIT_FILE="src/kernels/__init__.py"
echo "# Auto-generated kernel exports" > "$INIT_FILE"
echo "# DO NOT EDIT - Generated by build.sh" >> "$INIT_FILE"
echo "" >> "$INIT_FILE"

for dir in "${KERNEL_DIRS[@]}"; do
  find "$dir" -name "*.cl" | while read -r cl_file; do
    kernel_name=$(basename "$cl_file" .cl)
    py_name="${kernel_name}_kernel"

    py_file="src/kernels/${kernel_name}.py"
    {
      echo "def ${py_name}():"
      echo '    return r"""'"$(cat "$cl_file")"'"""'
    } > "$py_file"

    echo "from .${kernel_name} import ${py_name}" >> "$INIT_FILE"

    echo "generated $py_file"
  done
done

echo "" >> "$INIT_FILE"
echo "__all__ = [" >> "$INIT_FILE"
for dir in "${KERNEL_DIRS[@]}"; do
  find "$dir" -name "*.cl" | while read -r cl_file; do
    kernel_name=$(basename "$cl_file" .cl)
    echo "    '${kernel_name}_kernel'," >> "$INIT_FILE"
  done
done
echo "]" >> "$INIT_FILE"

echo "generated $INIT_FILE"
echo "kernel build complete"
