[project]
name = "opencl-kernels"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["numpy>=2.3.1", "pyopencl>=2025.2.4"]

[dependency-groups]
dev = ["ruff>=0.11.0"]

[tool.ruff]
line-length = 88
indent-width = 2
extend-exclude = ["test"]
